apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - foo'
  name: loki
  namespace: pgo
spec:
  rules:
  - host: pgo.open-accessibility.org
    http:
      paths:
      - backend:
          serviceName: loki
          servicePort: 3100
        path: /
  tls:
  - secretName: letsencrypt-prod
    hosts:
    - pgo.open-accessibility.org
