apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - foo'
  name: alertmanager
  namespace: pgo
spec:
  rules:
  - host: alertmanager.open-accessibility.org
    http:
      paths:
      - backend:
          serviceName: crunchy-alertmanager
          servicePort: 9093
        path: /
  tls:
  - secretName: letsencrypt-prod-alertmanager
    hosts:
    - alertmanager.open-accessibility.org
