apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - foo'
  name: prometheus
  namespace: monitoring
spec:
  rules:
  - host: prometheus.open-accessibility.org
    http:
      paths:
      - backend:
          serviceName: prometheus-server
          servicePort: 80
        path: /
  tls:
  - secretName: letsencrypt-prod
    hosts:
    - prometheus.open-accessibility.org
