---
global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 5s

scrape_configs:
- job_name: 'external-cluster'
  scrape_interval: 30s
  honor_labels: true
  metrics_path: '/federate'
  params:
    'match[]':
      - '{job="crunchy-postgres-exporter"}'
  static_configs:
    - targets:
      - '<ip>:9090'

rule_files:
  - /etc/prometheus/alert-rules.d/*.yml
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "<ip>:9093"